/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Manager;
import java.sql.*;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.view.*;
import net.sf.jasperreports.engine.*;
/**
 *
 * @author dessy yanty
 */
public class JFrameAccident extends javax.swing.JFrame {
    Connection con;
    Connection conex;
    Statement st;
    ResultSet rs;
    int j = 0,z = 0,kdp, gaji;
    String idk;
    
    /**
     * Creates new form JFrameAccident
     */
    public JFrameAccident() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        bersih();
        
        connect();
        tampildata();
        tampildata2();
    }

    public void connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con =DriverManager.getConnection("jdbc:mysql://localhost:3306/boomchipz","root","");
            conex =DriverManager.getConnection("jdbc:mysql://localhost:3306/boomchipz","root","");
            st = con.createStatement();
        }
        catch(ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
            System.out.println(e.getMessage());
        }
    }
    
    public void bersih() {
      
        jTextField3.setText("");
    }
    
    public void tampildata(){
        DefaultTableModel tbl1 = new DefaultTableModel();
        tbl1.addColumn("Kode Accident");
        tbl1.addColumn("Tanggal");
        tbl1.addColumn("ID Karyawan");
        tbl1.addColumn("Kode Makanan");
        tbl1.addColumn("Jumlah");
        tbl1.addColumn("Harga");
        tbl1.addColumn("Rugi");   
        try{
            connect();
             rs = st.executeQuery("Select * from t_accident");
            while (rs.next())
            {
                tbl1.addRow(new Object[]{
                rs.getString(1),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
                rs.getString(8)
            });
            }
            jTable2.setModel(tbl1);
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null,"Ada Kesalahan....");  
        }
        
    }
    public void tampildata2(){
        DefaultTableModel tbl1 = new DefaultTableModel();
        tbl1.addColumn("Kode Makanan");
        tbl1.addColumn("Nama Makanan/Minuman");
        tbl1.addColumn("Harga");
        tbl1.addColumn("Jumlah");
  
        try{
            connect();
             rs = st.executeQuery("select m.KdMakanan, NamaMakanan, Harga from t_menu m, t_resep r where m.KdMakanan = r.KdMakanan");
            while (rs.next())
            {
                tbl1.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),0
         
            });
            }
            jTable1.setModel(tbl1);
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null,"Ada Kesalahan....");  
        }
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACCIDENT");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Accident", "Tanggal", "ID Karyawan", "Kode Makanan", "Jumlah", "Harga", "Rugi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ID Karyawan");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText(":");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Makanan", "Nama Makanan/Minuman", "Harga", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Report ACC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id = jTextField3.getText();
        String kd = "",l="";
        int k, m;
             try{
        rs = st.executeQuery("select NoMeja, KdPesan from t_pesan where Status = 'On table' AND IDKaryawan = '"+id+"'");
        while(rs.next()){
           
            kdp = Integer.parseInt(rs.getString(2));
        }
        for(k = 0;k<jTable1.getRowCount();k++){
        l = jTable1.getValueAt(k,3).toString();
        m = Integer.parseInt(l);
            if(m != 0){
         kd = jTable1.getValueAt(k,0).toString();
   st = con.createStatement();

   rs = st.executeQuery("select NoPesanan from t_pesanan");
   while(rs.next()){
       if(Integer.parseInt(rs.getString(1)) > j){
  j = Integer.parseInt(rs.getString(1));
  
       }
   }
    j = j+1;
    st.executeUpdate("insert into t_pesanan values ("+j+","+kdp+",'"+kd+"',"+m+",'Waiting')");
    
   rs = st.executeQuery("select KdAcc, Rugi from t_accident");
   while(rs.next()){
       if(Integer.parseInt(rs.getString(1)) > z){
  z = Integer.parseInt(rs.getString(1));
  
       }
   }
    z = z+1;
    int select = jTable1.getSelectedRow();
    int h = Integer.parseInt(jTable1.getValueAt(select,2).toString());
    int rugi = m*h;
    st.executeUpdate("insert into t_accident values ("+z+",'"+kdp+"',sysdate(),'"+id+"','"+kd+"',"+m+" ,"+h+","+rugi+")");
    String sql = "SELECT z.IDKaryawan, GajiBulanIni FROM (SELECT t.IDKaryawan, NamaKaryawan, Jabatan, Alamat, NoTelepon, JenisKelamin, TanggalLahir, t.Gaji, a.Rugi, t.Gaji - a.Rugi AS GajiBulanIni FROM t_karyawan t, t_accident a WHERE t.IDKaryawan = a.IDKaryawan)z, t_karyawan x WHERE z.IDKaryawan = x.IDKaryawan";
    rs = st.executeQuery(sql);
    while(rs.next()){
        idk = rs.getString(1);
        gaji = Integer.parseInt(rs.getString(2));
    }
    connect();
    st.executeUpdate("insert into t_gaji values('"+idk+"',"+gaji+")");
        }
        }
    
             }
             catch(Exception e){
                 JOptionPane.showMessageDialog(null,"Data gagal di insert");
   }
   tampildata();             
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
                {
                    String REPORT = "C:\\Users\\Asus\\Desktop\\WOI JAVA KITA SELESAI COY!\\New folder\\BENAR BANGET\\UAS JAVA\\JavaRestaurants\\src\\Manager\\Report_acc.jrxml";
                    JasperReport JASP_REP= JasperCompileManager.compileReport(REPORT);
                    JasperPrint JASP_PRINT = JasperFillManager.fillReport(JASP_REP,null,conex);
                    JasperViewer.viewReport(JASP_PRINT);
                    
                }
               catch(Exception X) {System.out.print(X);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
