/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Cashier;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class JFrameSplit extends javax.swing.JFrame {
ResultSet rs;
Statement st;
Connection con;
private int kode,kode2;
int meja,nop,nop2;
String waiter;

    public JFrameSplit() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        connect();

    }
        
 public void setKode(int kd){
this.kode=kd;
}
 
public void setKodeSplit(int kds){
this.kode2=kds;
}
 
             public void connect() {
            try{
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/boomchipz", "root", "");
                st = con.createStatement();
                rs = st.executeQuery("select NoMeja, IDKaryawan from t_pesan where KdPesan = "+kode);
                while(rs.next()){
                meja = Integer.parseInt(rs.getString(1));
                waiter = rs.getString(2);
                st.executeUpdate("insert into t_pesan values ("+kode2+","+meja+",'"+waiter+"', now(), 'On table')");
    }
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Connection Failed");
            }
            
        }
  public void tampildata(){
       
        DefaultTableModel tbl1 = new DefaultTableModel();
        tbl1.addColumn("Kode");
        tbl1.addColumn("Item");
        tbl1.addColumn("Jumlah");
        tbl1.addColumn("Harga");
        tbl1.addColumn("Total");
  
        try{
             
             rs = st.executeQuery("SELECT s.KdMakanan, NamaMakanan, JumlahPesanan, Harga, JumlahPesanan * Harga, NoPesanan FROM (SELECT NoPesanan, p.KdPesan, NoMeja, pe.KdMakanan, JumlahPesanan, Harga, JumlahPesanan * Harga FROM t_pesan p, t_pesanan pe, t_menu m WHERE p.KdPesan = pe.KdPesan AND pe.KdMakanan = m.KdMakanan AND p.KdPesan = "+kode+") s, t_resep r WHERE s.KdMakanan = r.KdMakanan");
                while(rs.next()){
                tbl1.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5)      
            });
                nop = Integer.parseInt(rs.getString(6));
                }
                
            jTable1.setModel(tbl1);
       
        
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null,"Error");  
          
        }
       
    }
  
   public void tampildata2(){
       
        DefaultTableModel tbl2 = new DefaultTableModel();
        tbl2.addColumn("Kode");
        tbl2.addColumn("Item");
        tbl2.addColumn("Jumlah");
        tbl2.addColumn("Harga");
        tbl2.addColumn("Total");
  
        try{
             
             rs = st.executeQuery("SELECT s.KdMakanan, NamaMakanan, JumlahPesanan, Harga, JumlahPesanan * Harga, NoPesanan FROM (SELECT NoPesanan, p.KdPesan, NoMeja, pe.KdMakanan, JumlahPesanan, Harga, JumlahPesanan * Harga FROM t_pesan p, t_pesanan pe, t_menu m WHERE p.KdPesan = pe.KdPesan AND pe.KdMakanan = m.KdMakanan AND p.KdPesan = "+kode2+") s, t_resep r WHERE s.KdMakanan = r.KdMakanan");
                while(rs.next()){
                tbl2.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5)      
            });
                nop2 = Integer.parseInt(rs.getString(6));
                }
                
            jTable2.setModel(tbl2);
       
        
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null,"Error");  
          
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Makanan/Minuman", "Jumlah", "Harga", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusCycleRoot(true);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Makanan/Minuman", "Jumlah", "Harga", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setFocusCycleRoot(true);
        jTable2.setShowHorizontalLines(false);
        jTable2.setShowVerticalLines(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable2);

        jButton1.setText(">>>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SPLIT BILL");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Pay Bill 2");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    
    int select = jTable1.getSelectedRow();
    try{
    st.executeUpdate("update t_pesanan set KdPesan = "+kode2+" where NoPesanan = "+nop+" AND KdMakanan = '"+jTable1.getValueAt(select,0)+"' AND KdPesan = "+kode);
    }
    catch(Exception e){
   JOptionPane.showMessageDialog(null,"Error");  
   }
    tampildata();
    tampildata2();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    int select = jTable2.getSelectedRow();
    try{
    st.executeUpdate("update t_pesanan set KdPesan = "+kode+" where NoPesanan = "+nop2+" AND KdMakanan = '"+jTable1.getValueAt(select,0)+"' AND KdPesan = "+kode2);
    }
    catch(Exception e){
   JOptionPane.showMessageDialog(null,"Error");  
   }
    tampildata();
    tampildata2();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    JFrameCetakBill2 bill = new JFrameCetakBill2();
    bill.setKode(kode2);
    bill.tampildata();
    dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
