/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Kitchen;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dessy yanty
 */
public class JFrameKitchen extends javax.swing.JFrame {
Connection con;
Statement st;
ResultSet rs;
int jml,stk,selisih,masak,psn;
String brg,a;
    /**
     * Creates new form JFrameKitchen
     */
    public JFrameKitchen() {
        connect();
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        tampildata();
        
        
    }
    
    public void connect(){
            try{
            Class.forName("com.mysql.jdbc.Driver");
            con =DriverManager.getConnection("jdbc:mysql://localhost:3306/boomchipz","root","");
            st = con.createStatement();
           
        } catch(ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
            System.out.println(e.getMessage());
        }
    }
        
      public void tampildata(){
        DefaultTableModel tbl1 = new DefaultTableModel();
        tbl1.addColumn("No Pesanan");
       tbl1.addColumn("Kode Makanan/Minuman");
        tbl1.addColumn("Nama Makanan/Minuman");
        tbl1.addColumn("Jumlah");
        tbl1.addColumn("Status");
  
        try{
            connect();
             rs = st.executeQuery("Select NoPesanan, p.KdPesan, p.KdMakanan, NamaMakanan, JumlahPesanan, StatusMasak from t_pesanan p, t_resep r, t_pesan s where p.KdPesan = s.KdPesan AND p.KdMakanan = r.KdMakanan AND (StatusMasak = 'Waiting' OR StatusMasak = 'OTP')");
            while (rs.next())
            {
                tbl1.addRow(new Object[]{
                rs.getString(1),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
             
            });
            }
            jTable1.setModel(tbl1);
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null,"Ada Kesalahan....");  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KITCHEN");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("COOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("FINISH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Pesanan", "Kode Makanan/Minuman", "Nama Makanan/Minuman", "Jumlah", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{
    connect();
    int select = jTable1.getSelectedRow();
    st.executeUpdate("update t_pesanan set StatusMasak = 'OTP' where StatusMasak = 'Waiting' AND NoPesanan = "+jTable1.getValueAt(select,0));
    rs = st.executeQuery("select p.KdMakanan, b.KdBarang, Jumlah, JumlahStock, JumlahPesanan from t_pesanan p, t_bahan b, t_inventory i where p.KdMakanan = '"+jTable1.getValueAt(select,1)+"' AND p.KdMakanan = b.KdMakanan AND b.KdBarang = i.KdBarang");
    while(rs.next()){
     brg = rs.getString(2);
     jml = Integer.parseInt(rs.getString(3));
     stk = Integer.parseInt(rs.getString(4));
     psn = Integer.parseInt(rs.getString(5));
     masak = jml*psn;
     selisih = stk - masak;
     connect();
     st.executeUpdate("update t_inventory set JumlahStock = "+selisih+" where KdBarang = '"+brg+"'");
    st.executeUpdate("insert into t_inventorykeluar values('"+brg+"',"+masak+", sysdate())");}
    

  
    
    }
   catch(Exception e){
                e.printStackTrace();
            }
    tampildata();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    try{
    connect();
    int select = jTable1.getSelectedRow();
    String sql = "update t_pesanan set StatusMasak = 'Finish' where StatusMasak = 'OTP' AND NoPesanan = "+jTable1.getValueAt(select,0);
    st.executeUpdate(sql);
    }
   catch(Exception e){
                e.printStackTrace();
            }
    tampildata();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
