/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Waiters;

import java.awt.event.*;
import java.sql.*;
import javax.swing.JOptionPane;


public class JFrameNomorMeja extends javax.swing.JFrame {
String waiter;
int meja;
int i = 0,kd1,kd2,kd3,kd4;
Boolean b1=false,b2=false,b3=false,b4=false;
String w1 = "",w2="",w3="",w4="";
ResultSet rs;
Statement st;
Connection con;
    /**
     * Creates new form JFrameNomorMeja
     */
    public JFrameNomorMeja() {
        initComponents();
        connect();
        setLocationRelativeTo(null);
        setVisible(true);
       
      
       orderbtn.setEnabled(false);
       
        ActionListener radioActionPerformed = new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                 waiter = jComboBox1.getSelectedItem().toString();
                
                if(jRadioButton1.isSelected()){if(b1){takebtn.setEnabled(false);orderbtn.setEnabled(true);} else{takebtn.setEnabled(true);orderbtn.setEnabled(false); }}
                if(jRadioButton2.isSelected()){if(b2){takebtn.setEnabled(false);orderbtn.setEnabled(true);} else{takebtn.setEnabled(true);orderbtn.setEnabled(false); }}
                if(jRadioButton3.isSelected()){if(b3){takebtn.setEnabled(false);orderbtn.setEnabled(true);} else{takebtn.setEnabled(true);orderbtn.setEnabled(false); }}
                if(jRadioButton4.isSelected()){if(b4){takebtn.setEnabled(false);orderbtn.setEnabled(true);} else{takebtn.setEnabled(true);orderbtn.setEnabled(false); }}
                
            }
           
        };
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);
        buttonGroup1.add(jRadioButton4);
        jRadioButton1.addActionListener(radioActionPerformed);
        jRadioButton2.addActionListener(radioActionPerformed);
        jRadioButton3.addActionListener(radioActionPerformed);
        jRadioButton4.addActionListener(radioActionPerformed);
    }
    

     public void connect() {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/boomchipz", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("select IDKaryawan from t_karyawan where Jabatan='Waiter' AND StatusKaryawan = 'Hired'");
            jComboBox1.removeAllItems();
            while(rs.next()){
            jComboBox1.addItem(rs.getString(1));
            }
            
            rs = st.executeQuery("select NoMeja, KdPesan, IDKaryawan from t_pesan where Status = 'On table'");
            while(rs.next()){
                if(Integer.parseInt(rs.getString(1)) == 1){
                    b1 = true; kd1 = Integer.parseInt(rs.getString(2)); w1 = rs.getString(3);
                    if(jRadioButton1.isSelected()){
                        if(b1){
                            takebtn.setEnabled(false);orderbtn.setEnabled(true);}
                        else{takebtn.setEnabled(true);orderbtn.setEnabled(false); }}
                    }
                if(Integer.parseInt(rs.getString(1)) == 2){
                    b2 = true; kd2 = Integer.parseInt(rs.getString(2)); w2 = rs.getString(3);
                    if(jRadioButton2.isSelected()){
                        if(b2){
                            takebtn.setEnabled(false);orderbtn.setEnabled(true);}
                        else{takebtn.setEnabled(true);orderbtn.setEnabled(false); }}
                    }
                if(Integer.parseInt(rs.getString(1)) == 3){
                    b3 = true; kd3 = Integer.parseInt(rs.getString(2)); w3 = rs.getString(3);
                    if(jRadioButton3.isSelected()){
                        if(b3){
                            takebtn.setEnabled(false);orderbtn.setEnabled(true);}
                        else{takebtn.setEnabled(true);orderbtn.setEnabled(false); }}
                    }
                if(Integer.parseInt(rs.getString(1)) == 4){
                    b4 = true; kd4 = Integer.parseInt(rs.getString(2)); w4 = rs.getString(3);
                    if(jRadioButton4.isSelected()){
                        if(b4){
                            takebtn.setEnabled(false);orderbtn.setEnabled(true);}
                        else{takebtn.setEnabled(true);orderbtn.setEnabled(false); }}
                    }
                }
            }
            
            
        
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Connection Failed");
        }
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        orderbtn = new javax.swing.JButton();
        waitbtn = new javax.swing.JButton();
        takebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        viewbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nomor Meja");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        orderbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        orderbtn.setText("ORDER");
        orderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderbtnActionPerformed(evt);
            }
        });

        waitbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        waitbtn.setText("WAITING LIST");
        waitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitbtnActionPerformed(evt);
            }
        });

        takebtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        takebtn.setText("TAKE");
        takebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takebtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOMOR MEJA");

        viewbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewbtn.setText("VIEW ORDER");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID Waiter");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Meja 1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Meja 2");

        jRadioButton3.setText("Meja 3");

        jRadioButton4.setText("Meja 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(40, 40, 40)
                                .addComponent(jRadioButton2)))
                        .addGap(57, 57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(takebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(waitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(99, 99, 99))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(takebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(viewbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(waitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(orderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void takebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takebtnActionPerformed
  
   try{
   waiter = jComboBox1.getSelectedItem().toString();
   if(waiter.equals(w1) || waiter.equals(w2) || waiter.equals(w3) || waiter.equals(w4)){
   JOptionPane.showMessageDialog(this, "Satu pelayan hanya dilayani oleh satu meja!");
   }
   else {
       st = con.createStatement();
   rs = st.executeQuery("select KdPesan from t_pesan");
   while(rs.next()){
       if(Integer.parseInt(rs.getString(1)) > i){
  i = Integer.parseInt(rs.getString(1));
       }
   }
   i = i+1;
   if(jRadioButton1.isSelected()){b1=true;takebtn.setEnabled(false);orderbtn.setEnabled(true); w1= waiter; meja = 1; kd1 = i;
   st.executeUpdate("insert into t_pesan values ("+kd1+","+meja+",'"+waiter+"', now(), 'On table')");}
   if(jRadioButton2.isSelected()){b2=true;takebtn.setEnabled(false);orderbtn.setEnabled(true); w2= waiter; meja = 2; kd2 = i;
   st.executeUpdate("insert into t_pesan values ("+kd2+","+meja+",'"+waiter+"', now(), 'On table')");}
   if(jRadioButton3.isSelected()){b3=true;takebtn.setEnabled(false);orderbtn.setEnabled(true); w3= waiter; meja = 3; kd3 = i;
   st.executeUpdate("insert into t_pesan values ("+kd3+","+meja+",'"+waiter+"', now(), 'On table')");}
   if(jRadioButton4.isSelected()){b4=true;takebtn.setEnabled(false);orderbtn.setEnabled(true); w4= waiter; meja = 4; kd4 = i;
   st.executeUpdate("insert into t_pesan values ("+kd4+","+meja+",'"+waiter+"', now(), 'On table')");}

   }
   }
   catch(Exception e){
   e.printStackTrace();
   }
   
   
    
    }//GEN-LAST:event_takebtnActionPerformed

    private void orderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderbtnActionPerformed

      
JFrameMenu menu = new JFrameMenu();
if(jRadioButton1.isSelected()){
menu.setKodePesan(kd1);    
}
if(jRadioButton2.isSelected()){
menu.setKodePesan(kd2);    
}
if(jRadioButton3.isSelected()){
menu.setKodePesan(kd3);    
}
if(jRadioButton4.isSelected()){
menu.setKodePesan(kd4);    
}

    }//GEN-LAST:event_orderbtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
    JFrameViewOrder view = new JFrameViewOrder();
    }//GEN-LAST:event_viewbtnActionPerformed

    private void waitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitbtnActionPerformed
    JFrameWaitingList wait = new JFrameWaitingList();
    }//GEN-LAST:event_waitbtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JRadioButton jRadioButton3;
    public javax.swing.JRadioButton jRadioButton4;
    public javax.swing.JButton orderbtn;
    public javax.swing.JButton takebtn;
    private javax.swing.JButton viewbtn;
    private javax.swing.JButton waitbtn;
    // End of variables declaration//GEN-END:variables






}
